/* Spanish: Communication skills. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js.
   Listening questions use L(question, text): the Listen button reads the text aloud. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['hola','hello',,' hello | hi '],['adiós','goodbye',,' goodbye | bye '],['por favor','please'],['gracias','thank you',,' thank you | thanks '],['buenos días','good morning',,' good morning | good day '],['buenas noches','good night',,' good night | goodnight | good evening '],['lo siento','I am sorry',,' sorry '],['de nada','you are welcome',,' welcome | no problem | not at all | don t mention it '],['hasta luego','see you later',,' see you later | see you soon | see you '],['perdón','excuse me',,' excuse me | sorry | pardon ']],
W2=[['¿Cómo estás?','How are you?',' como estas ',' how are you '],['¿Dónde vives?','Where do you live?',' donde vives ',' where do you live '],['¿Cuántos años tienes?','How old are you?',' cuantos anos tienes ',' how old are you '],['¿Qué hora es?','What time is it?',' que hora es ',' what time is it | what is the time | what s the time '],['¿Cuánto cuesta?','How much does it cost?',' cuanto cuesta ',' how much '],['No entiendo','I do not understand',' no entiendo | no comprendo ',' understand '],['¿Puedes repetir?','Can you repeat?',' puedes repetir ',' repeat | say that again | say it again '],['¿Cómo se dice…?','How do you say…?',' como se dice ',' how do you say '],['Más despacio, por favor','More slowly, please',' mas despacio ',' slow | slowly '],['¿Qué significa…?','What does … mean?',' que significa ',' what does | mean ']],
Q=(q,o,m,s)=>()=>L(M(q,o,m+` The Spanish was: "${s}"`),s),
D=(n,s,kw)=>()=>L(T(`Listen and type the Spanish sentence you hear. (Sentence ${n})`,kw,s,`Listen as many times as you need. You do not need to type the accents.`),s),
R1=`Hola Marta: Esta tarde no puedo ir al parque porque tengo que hacer los deberes. ¿Quieres ir al cine mañana a las seis? Hasta luego, Ana.`,
R2=`Estimado señor: Le escribo porque la semana pasada compré una camiseta en su tienda y, al llegar a casa, vi que era demasiado pequeña. Quisiera cambiarla por una talla más grande. Si no es posible, prefiero que me devuelvan el dinero. Atentamente, Carlos Ruiz.`;
BANK.Spanish['Communication skills']=[
/* Easy */[mcEn(W1),toEn(W1),toEs(W1),
one(Q(`Listen. How is the speaker feeling?`,[`very well`,`tired`,`ill`,`sad`],`"Muy bien" means "very well".`,`Hola, estoy muy bien, gracias.`),
Q(`Listen. What is the speaker's name?`,[`Pedro`,`Pablo`,`Paco`,`Pilar`],`"Me llamo…" means "my name is…".`,`Buenos días. Me llamo Pedro.`),
Q(`Listen. How old is the speaker?`,[`12`,`2`,`20`,`10`],`"Doce" is 12.`,`Tengo doce años.`),
Q(`Listen. What does the speaker like?`,[`chocolate`,`cheese`,`chicken`,`cherries`],`"Me gusta mucho" means "I really like".`,`Me gusta mucho el chocolate.`))],
/* Moderate */[mcEn(W2),toEn(W2),
one(Q(`Listen. How many brothers and sisters does the speaker have altogether?`,[`3`,`2`,`1`,`4`],`Two brothers and one sister make three.`,`Tengo dos hermanos y una hermana.`),
Q(`Listen. Where does the speaker live?`,[`in a small village`,`in a big city`,`near the beach`,`in the mountains`],`"Un pueblo pequeño" means "a small village".`,`Vivo en un pueblo pequeño en el norte de España.`),
Q(`Listen. What time does the lesson start?`,[`9:30`,`9:15`,`8:30`,`9:00`],`"Las nueve y media" means "half past nine".`,`La clase empieza a las nueve y media.`)),
one(D(1,`Me gusta el fútbol.`,[` me gusta `,` futbol `]),D(2,`Tengo un perro negro.`,[` tengo `,` perro `,` negro `]),D(3,`Vivo en una casa grande.`,[` vivo `,` casa `,` grande `])),
one(rd(R1,`Why can Ana not go to the park this afternoon?`,[`She has to do her homework`,`She is ill`,`It is raining`,`She is going to the cinema`],`"Tengo que hacer los deberes" means "I have to do my homework".`),
rd(R1,`What does Ana suggest?`,[`going to the cinema tomorrow at six`,`going to the park tomorrow`,`doing homework together`,`going to the cinema this afternoon`],`"¿Quieres ir al cine mañana a las seis?"`),
rd(R1,`What kind of text is this?`,[`an informal message to a friend`,`a formal letter`,`a newspaper article`,`an advert`],`It starts with "Hola" and ends with "Hasta luego".`))],
/* Difficult */[toEs(W2),
one(Q(`Listen. What did the speaker do yesterday?`,[`went to the beach with friends`,`went to school`,`stayed at home`,`went shopping with family`],`"Fui a la playa con mis amigos" means "I went to the beach with my friends".`,`Ayer fui a la playa con mis amigos y nadé en el mar.`),
Q(`Listen. Why does the speaker like Spanish?`,[`It is useful and the teacher is nice`,`It is easy`,`There is no homework`,`Their friends study it`],`"Útil" means "useful" and "simpática" means "nice".`,`Me gusta el español porque es útil y la profesora es simpática.`),
Q(`Listen. What is the weather going to be like tomorrow?`,[`rainy and cold`,`sunny and hot`,`windy and sunny`,`snowy`],`"Va a llover" means "it is going to rain".`,`Mañana va a llover y va a hacer frío.`)),
one(D(4,`Mi hermano juega al tenis los sábados.`,[` hermano `,` juega `,` tenis `,` sabados `]),D(5,`Ayer comí pollo con arroz.`,[` ayer `,` comi `,` pollo `,` arroz `]),D(6,`Voy a visitar a mis abuelos.`,[` voy a visitar `,` abuelos `])),
one(tE(`¿Puedes hablar más despacio, por favor?`,[`can|could`,`speak|talk`,`slow`,`please`],`Can you speak more slowly, please?`),
tE(`No entiendo la pregunta. ¿Puedes repetir?`,[`understand`,`question`,`repeat|again`],`I don't understand the question. Can you repeat it?`),
tE(`¿Cómo se dice "homework" en español?`,[`how`,`say`,`spanish`],`How do you say "homework" in Spanish?`)),
one(()=>M(`You want to speak politely to a teacher you do not know well. Which form of "you" should you use?`,[`usted`,`tú`,`vosotros`,`yo`],`"Usted" is the formal, polite form; "tú" is for friends and family.`),
()=>M(`In Spanish, a question in writing begins with…`,[`an upside-down question mark (¿)`,`a capital letter only`,`an exclamation mark`,`the word "pregunta"`],`Spanish questions are written with ¿ at the start and ? at the end.`),
()=>M(`Which letter is silent in Spanish words such as "hola" and "hermano"?`,[`h`,`o`,`l`,`r`],`The letter "h" is never pronounced in Spanish.`))],
/* Very Difficult */[
one(Q(`Listen. Why did the speaker not go to the party?`,[`She was ill`,`She had homework`,`She was not invited`,`She was on holiday`],`"Estaba enferma" means "I was ill".`,`Quería ir a la fiesta de Laura, pero no fui porque estaba enferma.`),
Q(`Listen. What will the speaker do if the weather is good?`,[`go to the beach`,`go to the cinema`,`stay at home`,`play tennis`],`"Si hace buen tiempo, iremos a la playa; si no, iremos al cine".`,`Si hace buen tiempo, iremos a la playa; si no, iremos al cine.`),
Q(`Listen. What does the speaker think of the film?`,[`It was too long, although the actors were good`,`It was excellent in every way`,`It was short and boring`,`The actors were bad`],`"Aunque" means "although"; "demasiado larga" means "too long".`,`Aunque los actores eran buenos, la película era demasiado larga.`)),
one(D(7,`El año pasado fuimos a México en avión.`,[` ano pasado `,` fuimos `,` mexico `,` avion `]),D(8,`Me gustaría ser médico porque quiero ayudar a la gente.`,[` me gustaria `,` medico `,` porque `,` ayudar `]),D(9,`Cuando era pequeño vivía en un pueblo.`,[` cuando era `,` pequeno `,` vivia `,` pueblo `])),
one(rd(R2,`Why is Carlos writing?`,[`The T-shirt he bought is too small`,`The T-shirt was too expensive`,`The shop was closed`,`He lost his receipt`],`"Vi que era demasiado pequeña" means "I saw that it was too small".`),
rd(R2,`What would Carlos like first of all?`,[`to exchange it for a larger size`,`to get his money back`,`to buy another colour`,`to speak to the manager`],`"Quisiera cambiarla por una talla más grande". A refund is only his second choice.`),
rd(R2,`How can you tell this is a formal letter?`,[`It uses "Estimado señor", "Le" and "Atentamente"`,`It uses "Hola" and "tú"`,`It is very short`,`It has no greeting`],`Formal Spanish uses the "usted" forms and set phrases such as "Atentamente".`)),
one(tS(`Excuse me, can you help me? I do not understand this word.`,[` perdon | perdone | disculpe `,` ayudar`,` no entiendo | no comprendo `,` palabra `],`Perdón, ¿puedes ayudarme? No entiendo esta palabra.`),
tS(`Could you repeat the question more slowly, please?`,[` puede | puedes | podria | podrias `,` repetir `,` pregunta `,` despacio | lentamente `],`¿Puede repetir la pregunta más despacio, por favor?`),
tS(`I am writing to you because I would like some information about the hotel.`,[` escribo `,` porque `,` me gustaria | quisiera `,` informacion `,` hotel `],`Le escribo porque quisiera información sobre el hotel.`))]]})();
