/* Spanish: Culture & festivals. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['la fiesta','festival',,' festival | party | celebration | fiesta '],['la Navidad','Christmas'],['el cumpleaños','birthday'],['el regalo','present',,' present | gift '],['la música','music'],['el baile','dance',,' dance | dancing '],['la comida','food',,' food | meal | lunch '],['la familia','family'],['el país','country'],['la bandera','flag']],
W2=[['celebrar','to celebrate'],['los fuegos artificiales','fireworks',' fuegos artificiales '],['el desfile','parade',,' parade | procession '],['el disfraz','costume',,' costume | fancy dress | disguise '],['la tradición','tradition'],['la Semana Santa','Easter',,' easter | holy week '],['la Nochevieja','New Year\'s Eve',,' new year '],['el Día de los Muertos','Day of the Dead',' dia de los muertos | dia de muertos ',' day of the dead '],['las uvas','grapes'],['la costumbre','custom',,' custom | habit | tradition ']],
W3=[['se celebra','it is celebrated',,' celebrated '],['tiene lugar','it takes place',,' takes place | happens '],['la gente','people'],['lanzar','to throw'],['llevar','to wear',,' wear | carry | take '],['típico','typical',' tipic',' typical | traditional '],['antiguo','old',' antigu',' old | ancient '],['famoso','famous',' famos',' famous | well-known | well known '],['hispanohablante','Spanish-speaking',,' spanish-speaking | spanish speaking '],['el mundo','world']],
R1=`La Tomatina es una fiesta muy famosa que se celebra en Buñol, un pueblo cerca de Valencia. Tiene lugar el último miércoles de agosto. Durante una hora, miles de personas lanzan tomates en la calle.`,
R2=`En México, el Día de los Muertos se celebra el uno y el dos de noviembre. No es una fiesta triste: las familias recuerdan a sus parientes muertos con comida, flores y música. Muchos turistas piensan que es igual que Halloween, pero en realidad las dos tradiciones son muy diferentes.`;
BANK.Spanish['Culture & festivals']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),
one(()=>M(`Which of these countries is Spanish-speaking?`,[`Mexico`,`Brazil`,`Portugal`,`Italy`],`Spanish is spoken in Mexico. Portuguese is spoken in Brazil and Portugal.`),
()=>M(`What is the capital city of Spain?`,[`Madrid`,`Barcelona`,`Seville`,`Lisbon`],`Madrid is the capital; Lisbon is the capital of Portugal.`),
()=>M(`"¡Feliz cumpleaños!" means…`,[`Happy birthday!`,`Merry Christmas!`,`Happy New Year!`,`Good luck!`],`"Feliz" means "happy" and "cumpleaños" means "birthday".`),
()=>M(`In which continent are Argentina, Chile and Peru?`,[`South America`,`Europe`,`Africa`,`Asia`],`Spanish is the main language of most of South and Central America.`))],
/* Moderate */[toEs(W1),toEn(W2),mcEn(W2),
one(tE(`Celebramos la Navidad con la familia.`,[`celebrate`,`christmas`,`family`],`We celebrate Christmas with the family.`),
tE(`En la fiesta hay música, baile y fuegos artificiales.`,[`music`,`danc`,`firework`],`At the festival there is music, dancing and fireworks.`),
tE(`Mi fiesta favorita es mi cumpleaños porque recibo regalos.`,[`favourite|favorite`,`birthday`,`present|gift`],`My favourite celebration is my birthday because I receive presents.`)),
one(()=>M(`On New Year's Eve (Nochevieja), many Spanish people eat twelve…`,[`grapes`,`tomatoes`,`cakes`,`oranges`],`They eat one grape for each chime of the clock at midnight.`),
()=>M(`La Tomatina is a festival where people throw…`,[`tomatoes`,`water`,`flowers`,`oranges`],`It takes place in Buñol, near Valencia, in August.`),
()=>M(`In Spain, children traditionally receive presents on 6 January from…`,[`the Three Kings`,`Father Christmas only`,`the Easter Bunny`,`their teachers`],`"El Día de Reyes" celebrates the Three Kings (los Reyes Magos).`))],
/* Difficult */[toEs(W2),toEn(W3),
one(tS(`We celebrate my birthday with a party.`,[` celebramos `,` cumpleanos `,` fiesta `],`Celebramos mi cumpleaños con una fiesta.`),
tS(`The festival takes place in August.`,[` fiesta | festival `,` tiene lugar | se celebra | es `,` agosto `],`La fiesta tiene lugar en agosto.`),
tS(`Last year I went to a festival and I saw the fireworks.`,[` ano pasado `,` fui `,` vi `,` fuegos artificiales `],`El año pasado fui a una fiesta y vi los fuegos artificiales.`)),
one(rd(R1,`Where is La Tomatina celebrated?`,[`in Buñol, near Valencia`,`in Madrid`,`in Mexico`,`in Barcelona`],`"Se celebra en Buñol, un pueblo cerca de Valencia".`),
rd(R1,`When does it take place?`,[`on the last Wednesday of August`,`on the first Wednesday of August`,`on the last day of August`,`every Wednesday in summer`],`"El último miércoles de agosto".`),
rd(R1,`How long do people throw tomatoes for?`,[`one hour`,`one day`,`one week`,`all night`],`"Durante una hora" means "for one hour".`))],
/* Very Difficult */[
one(rd(R2,`When is the Day of the Dead celebrated?`,[`1 and 2 November`,`31 October`,`2 December`,`1 January`],`"El uno y el dos de noviembre".`),
rd(R2,`What is the mood of the festival, according to the text?`,[`It is not a sad festival`,`It is a very sad festival`,`It is a frightening festival`,`It is a quiet festival`],`"No es una fiesta triste".`),
rd(R2,`What mistake do many tourists make?`,[`They think it is the same as Halloween`,`They think it is in Spain`,`They arrive in October`,`They do not bring flowers`],`"Piensan que es igual que Halloween, pero… son muy diferentes".`)),
one(tS(`In Spain, people eat twelve grapes on New Year's Eve.`,[` espana `,` gente | espanoles | personas | se comen `,` doce uvas `,` nochevieja `],`En España, la gente come doce uvas en Nochevieja.`),
tS(`It is an old tradition that is celebrated every year.`,[` tradicion `,` antigua `,` se celebra `,` cada ano | todos los anos `],`Es una tradición antigua que se celebra cada año.`),
tS(`I would like to visit Mexico to see the Day of the Dead.`,[` me gustaria | quisiera `,` visitar | ir a `,` mexico `,` dia de los muertos | dia de muertos `],`Me gustaría visitar México para ver el Día de los Muertos.`)),
one(wr(`Write a sentence in Spanish describing how you celebrate your birthday or another special day.`,[` celebr| fiesta | cumpleanos | navidad `,` con | y | comemos | recibo | hay `],`Celebro mi cumpleaños con una fiesta en casa y como tarta con mis amigos.`),
wr(`Write a sentence in Spanish giving your opinion of a festival, with a reason.`,[ES.OP+`| es `,ES.BC],`Me encanta la Navidad porque paso tiempo con mi familia.`),
wr(`Write a sentence in Spanish naming a Spanish-speaking country you would like to visit and why.`,[` me gustaria | quisiera | quiero `,ES.BC],`Me gustaría visitar Argentina porque quiero ver las montañas.`)),
one(()=>M(`How do the traditions of "el Día de Reyes" and Christmas Day in the UK compare?`,[`Both involve giving presents, but on different dates`,`They are on the same date`,`Neither involves presents`,`Día de Reyes is in summer`],`Día de Reyes is on 6 January.`),
()=>M(`Which language, besides Spanish, is an official language in part of Spain?`,[`Catalan`,`Portuguese`,`Italian`,`Arabic`],`Catalan, Basque and Galician are official in some regions.`),
()=>M(`Flamenco music and dance come originally from which region of Spain?`,[`Andalusia`,`Catalonia`,`Galicia`,`the Basque Country`],`Andalusia (Andalucía) is in the south of Spain.`))]]})();
