/* Spanish: Environment & world. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['el sol','sun'],['la lluvia','rain'],['la nieve','snow'],['el viento','wind'],['el calor','heat',,' heat | hot '],['el frío','cold'],['el mar','sea'],['el río','river'],['el árbol','tree'],['el cielo','sky']],
W2=[['hace sol','it is sunny',,' sunny '],['hace frío','it is cold',,' cold '],['hace calor','it is hot',,' hot '],['llueve','it is raining',,' raining | rains '],['nieva','it is snowing',,' snowing | snows '],['hace viento','it is windy',,' windy '],['está nublado','it is cloudy',' nublado ',' cloudy '],['hay tormenta','it is stormy',,' storm | stormy '],['el tiempo','weather'],['el clima','climate']],
W3=[['el medio ambiente','environment',' medio ambiente '],['la basura','rubbish',,' rubbish | litter | trash | garbage '],['reciclar','to recycle'],['la contaminación','pollution'],['ahorrar','to save'],['el cambio climático','climate change',' cambio climatico '],['proteger','to protect'],['apagar','to turn off',,' turn off | switch off '],['el plástico','plastic'],['la energía','energy']],
R1=`En el norte de España llueve mucho y hace fresco, incluso en verano. En cambio, en el sur hace mucho calor y casi nunca llueve. Por eso muchos turistas prefieren ir al sur en agosto.`,
R2=`En mi casa intentamos proteger el medio ambiente. Reciclamos el papel y el plástico, y mi madre va al trabajo en bicicleta. Yo debería ducharme en menos tiempo para ahorrar agua, pero me cuesta mucho. El problema más grave de mi ciudad es la contaminación del aire causada por los coches.`;
BANK.Spanish['Environment & world']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),mcEn(W2)],
/* Moderate */[toEs(W1),toEn(W2),toEs(W2),
one(tE(`En invierno hace frío y a veces nieva.`,[`winter`,`cold`,`sometimes`,`snow`],`In winter it is cold and sometimes it snows.`),
tE(`Hoy hace sol pero hace viento.`,[`today`,`sunny`,`windy`],`Today it is sunny but it is windy.`),
tE(`Me gusta el verano porque hace calor.`,[`like`,`summer`,`hot`],`I like the summer because it is hot.`)),
one(()=>M(`Which season is "el otoño"?`,[`autumn`,`spring`,`summer`,`winter`],`The seasons are la primavera, el verano, el otoño and el invierno.`),
()=>M(`Choose the correct phrase for "It is raining".`,[`Llueve`,`Nieva`,`Hace sol`,`Hace viento`],`"Llover" means "to rain".`),
()=>M(`"¿Qué tiempo hace?" means…`,[`What is the weather like?`,`What time is it?`,`How much time is there?`,`What are you doing?`],`"Tiempo" can mean both "weather" and "time".`))],
/* Difficult */[toEs(W3),toEn(W3),
one(tS(`We must protect the environment.`,[` debemos | hay que | tenemos que | se debe `,` proteger `,` medio ambiente `],`Debemos proteger el medio ambiente.`),
tS(`I recycle plastic and paper at home.`,[` reciclo `,` plastico `,` papel `,` casa `],`Reciclo el plástico y el papel en casa.`),
tS(`Yesterday it rained a lot and it was cold.`,[` ayer `,` llovio `,` mucho `,` hizo frio | hacia frio `],`Ayer llovió mucho e hizo frío.`)),
one(rd(R1,`What is the weather like in the north of Spain?`,[`rainy and cool`,`hot and dry`,`snowy all year`,`windy and hot`],`"Llueve mucho y hace fresco" means "it rains a lot and it is cool".`),
rd(R1,`How often does it rain in the south?`,[`almost never`,`every day`,`only in summer`,`every week`],`"Casi nunca llueve" means "it almost never rains".`),
rd(R1,`Why do many tourists go south in August?`,[`It is hot and dry there`,`It is cheaper`,`It is cooler`,`There are fewer people`],`"Por eso" (that is why) links their choice to the hot, dry weather.`))],
/* Very Difficult */[
one(rd(R2,`How does the writer's mother travel to work?`,[`by bicycle`,`by car`,`by bus`,`on foot`],`"Va al trabajo en bicicleta".`),
rd(R2,`What does the writer find difficult?`,[`taking shorter showers`,`recycling paper`,`cycling to school`,`turning off lights`],`"Debería ducharme en menos tiempo… pero me cuesta mucho": I should take shorter showers, but I find it hard.`),
rd(R2,`What is the most serious problem in the writer's city?`,[`air pollution from cars`,`too much rubbish`,`a lack of water`,`too much plastic`],`"La contaminación del aire causada por los coches".`)),
one(tS(`If we do not recycle, there will be more rubbish.`,[` si `,` no reciclamos `,` habra `,` mas basura `],`Si no reciclamos, habrá más basura.`),
tS(`To save energy, you should turn off the lights.`,[` para ahorrar energia `,` debes | deberias | hay que | se debe | tienes que `,` apagar `,` luces | luz `],`Para ahorrar energía, debes apagar las luces.`),
tS(`Climate change is the most serious problem in the world.`,[` cambio climatico `,` problema `,` mas grave | mas serio `,` mundo `],`El cambio climático es el problema más grave del mundo.`)),
one(wr(`Write a sentence in Spanish saying what the weather is like today.`,[` hace | llueve | nieva | esta nublado | hay `],`Hoy hace sol pero hace un poco de frío.`),
wr(`Write a sentence in Spanish saying one thing you do to protect the environment.`,[` reciclo | ahorro | apago | voy | uso | no uso | reutilizo | camino | reciclamos | intento `],`Para proteger el medio ambiente, reciclo el plástico y voy al colegio a pie.`),
wr(`Write a sentence in Spanish saying what people should do to help the environment, using "hay que", "debemos" or "se debe".`,[` hay que | debemos | se debe | deberiamos | tenemos que `],`Debemos usar menos plástico y hay que ahorrar agua.`)),
conj('fut',[0,2,4,6])]]})();
