/* Spanish: Food & healthy living. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['el pan','bread'],['el queso','cheese'],['el pollo','chicken'],['el pescado','fish'],['la manzana','apple'],['el agua','water'],['la leche','milk'],['el huevo','egg'],['el arroz','rice'],['la carne','meat']],
W2=[['el desayuno','breakfast'],['el almuerzo','lunch'],['la cena','dinner',,' dinner | supper | evening meal | tea '],['las verduras','vegetables',,' vegetables | veg | greens '],['la fruta','fruit'],['los dulces','sweets',,' sweets | candy | candies '],['la ensalada','salad'],['el zumo','juice'],['las patatas fritas','chips',,' chips | fries | crisps | french fries '],['el helado','ice cream',,' ice cream | ice-cream | icecream ']],
W3=[['sano','healthy',' san| saludable'],['malsano','unhealthy',' malsan| poco saludable'],['rico','tasty',' ric| delicios| sabros',' tasty | delicious | yummy | nice '],['tengo hambre','I am hungry',,' hungry '],['tengo sed','I am thirsty',,' thirsty '],['hacer ejercicio','to do exercise',,' exercise '],['dormir bien','to sleep well',,' sleep well '],['beber agua','to drink water',,' drink water '],['evitar','to avoid'],['demasiado','too much',' demasiad',' too much | too many ']],
R1=`Para el desayuno tomo cereales con leche y un zumo de naranja. Al mediodía como en el colegio: normalmente pollo con arroz o pescado con ensalada. No como muchos dulces porque son malos para los dientes.`,
R2=`Mi médico dice que debería comer cinco porciones de fruta y verdura al día, pero la verdad es que solo como dos o tres. Además, bebo demasiados refrescos. Desde la semana pasada intento beber más agua y voy al colegio andando en vez de ir en autobús.`;
BANK.Spanish['Food & healthy living']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),mcEn(W2)],
/* Moderate */[toEs(W1),toEn(W2),mcEn(W3),
one(tE(`Desayuno pan con queso y bebo leche.`,[`breakfast`,`bread`,`cheese`,`milk`],`For breakfast I have bread with cheese and I drink milk.`),
tE(`Me gusta el pollo pero odio el pescado.`,[`like`,`chicken`,`hate`,`fish`],`I like chicken but I hate fish.`),
tE(`Las verduras son muy sanas.`,[`vegetable|veg`,`healthy|good for you`],`Vegetables are very healthy.`)),
one(()=>M(`Choose the correct word: "Me ______ las manzanas."`,[`gustan`,`gusta`,`gusto`,`gustas`],`"Gustan" is used because "las manzanas" is plural.`),
()=>M(`"Tengo hambre" means…`,[`I am hungry`,`I am thirsty`,`I am tired`,`I am cold`],`Spanish uses "tener" (to have): "I have hunger".`),
()=>M(`In a café, how do you say "I would like a cheese sandwich"?`,[`Quisiera un bocadillo de queso`,`Tengo un bocadillo de queso`,`Odio el bocadillo de queso`,`Hay un bocadillo de queso`],`"Quisiera" is a polite way to say "I would like".`))],
/* Difficult */[toEs(W2),toEs(W3),
one(tS(`I eat fruit every day because it is healthy.`,[` como `,` fruta `,` todos los dias | cada dia `,` porque `,` san| saludable`],`Como fruta todos los días porque es sana.`),
tS(`Yesterday I ate chicken with rice.`,[` ayer `,` comi `,` pollo `,` arroz `],`Ayer comí pollo con arroz.`),
tS(`You should drink a lot of water.`,[` debes | deberias | hay que | tienes que | se debe `,` beber `,` agua `],`Debes beber mucha agua.`)),
one(rd(R1,`What does the writer drink at breakfast?`,[`orange juice`,`milk on its own`,`water`,`tea`],`"Un zumo de naranja" means "an orange juice".`),
rd(R1,`Where does the writer eat at midday?`,[`at school`,`at home`,`in a café`,`at a friend's house`],`"Como en el colegio" means "I eat at school".`),
rd(R1,`Why does the writer not eat many sweets?`,[`They are bad for the teeth`,`They are expensive`,`They do not taste nice`,`They are not allowed at school`],`"Son malos para los dientes" means "they are bad for the teeth".`))],
/* Very Difficult */[
one(rd(R2,`How many portions of fruit and vegetables does the writer actually eat each day?`,[`two or three`,`five`,`none`,`more than five`],`The doctor recommends five, but "solo como dos o tres" means "I only eat two or three".`),
rd(R2,`What does the writer drink too much of?`,[`fizzy drinks`,`water`,`coffee`,`milk`],`"Demasiados refrescos" means "too many fizzy drinks".`),
rd(R2,`What change has the writer made since last week?`,[`walking to school instead of taking the bus`,`eating five portions of fruit`,`going to the gym`,`cycling to school`],`"Voy al colegio andando en vez de ir en autobús".`)),
one(tS(`To be healthy, you have to do exercise and sleep well.`,[` para `,` hay que | tienes que | debes | se debe `,` ejercicio | deporte `,` dormir bien `],`Para estar sano, hay que hacer ejercicio y dormir bien.`),
tS(`I used to eat a lot of sweets, but now I prefer fruit.`,[` comia `,` dulces | caramelos `,` ahora `,` prefiero `,` fruta `],`Antes comía muchos dulces, pero ahora prefiero la fruta.`),
tS(`Tomorrow I am going to cook fish with vegetables.`,[` manana `,` voy a cocinar | cocinare | voy a preparar `,` pescado `,` verduras `],`Mañana voy a cocinar pescado con verduras.`)),
one(wr(`Write a sentence in Spanish saying what you normally eat for breakfast or lunch.`,[` como | tomo | desayuno | almuerzo | bebo `],`Normalmente desayuno tostadas y bebo un zumo de naranja.`),
wr(`Write a sentence in Spanish giving advice for a healthy life, using "hay que", "debes" or "se debe".`,[` hay que | debes | se debe | deberias | tienes que `],`Para llevar una vida sana, hay que comer fruta y hacer deporte.`),
wr(`Write a sentence in Spanish saying which food you like or dislike, and why.`,[ES.OP+`| me gustan| no me gustan| me encantan`,ES.BC],`No me gustan las verduras porque son aburridas, pero me encanta el arroz.`)),
ES.numFig(31,99)]]})();
