/* Spanish: Free time & activities. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['el fútbol','football',,' football | soccer '],['la natación','swimming'],['el baloncesto','basketball'],['el tenis','tennis'],['la música','music'],['el cine','cinema',,' cinema | movies | movie theatre | movie theater '],['los videojuegos','video games',,' video games | videogames | computer games '],['el ciclismo','cycling'],['la lectura','reading'],['el baile','dancing',,' dancing | dance ']],
W2=[['jugar','to play'],['nadar','to swim'],['leer','to read'],['bailar','to dance'],['cantar','to sing'],['escuchar música','to listen to music',,' listen to music | listening to music '],['ver la tele','to watch TV',' ver la tele',' watch tv | watch television | watching tv | watch the tv | watch telly '],['salir con amigos','to go out with friends',,' go out with friends | going out with friends | go out with my friends '],['montar en bici','to ride a bike',' montar en bici',' ride a bike | cycle | go cycling | ride my bike | riding a bike '],['tocar la guitarra','to play the guitar',,' play the guitar | play guitar | playing the guitar ']],
W3=[['me encanta','I love',,' i love | i really like '],['odio','I hate'],['prefiero','I prefer'],['a veces','sometimes'],['nunca','never'],['todos los días','every day',,' every day | everyday | each day | daily '],['el fin de semana','the weekend',' fin de semana '],['aburrido','boring',' aburrid'],['emocionante','exciting'],['relajante','relaxing']],
R1=`Los sábados por la mañana juego al tenis con mi padre. Por la tarde voy al cine con mis amigos o escucho música en casa. Los domingos no hago deporte porque estoy cansado.`,
R2=`Antes jugaba al fútbol todos los días, pero el año pasado me rompí la pierna y ahora prefiero la natación. Mi hermano dice que el fútbol es más emocionante; sin embargo, yo creo que nadar es mejor para la salud.`;
BANK.Spanish['Free time & activities']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),
one(()=>M(`"Me gusta jugar al tenis" means…`,[`I like playing tennis`,`I hate tennis`,`I play tennis badly`,`I watch tennis`],`"Me gusta" + infinitive means "I like doing…".`),
()=>M(`"No me gusta nada el fútbol" means…`,[`I don't like football at all`,`I really like football`,`I never play football`,`I only like football`],`"No me gusta nada" means "I don't like … at all".`),
()=>M(`Which phrase means "in my free time"?`,[`en mi tiempo libre`,`en mi casa`,`por la mañana`,`en el colegio`],`"Tiempo libre" means "free time".`))],
/* Moderate */[toEs(W1),mcEn(W2),toEn(W3),
one(tE(`Juego al baloncesto los sábados.`,[`play`,`basketball`,`saturday`],`I play basketball on Saturdays.`),
tE(`Me encanta escuchar música en mi dormitorio.`,[`love|really like`,`music`,`bedroom|room`],`I love listening to music in my bedroom.`),
tE(`Nunca veo la tele por la mañana.`,[`never`,`tv|television|telly`,`morning`],`I never watch TV in the morning.`)),
conj('pres',[0,1,2,3,6])],
/* Difficult */[toEs(W2),toEs(W3),
one(tS(`I play football with my friends at the weekend.`,[` juego `,` futbol `,` amigos `,` fin de semana `],`Juego al fútbol con mis amigos el fin de semana.`),
tS(`I love swimming because it is relaxing.`,[` me encanta`,` nadar | natacion `,` porque `,` relajante `],`Me encanta nadar porque es relajante.`),
tS(`Yesterday I watched a film at the cinema.`,[` ayer `,` vi `,` pelicula `,` cine `],`Ayer vi una película en el cine.`)),
one(rd(R1,`When does the writer play tennis?`,[`on Saturday mornings`,`on Saturday afternoons`,`on Sunday mornings`,`every day`],`"Los sábados por la mañana" means "on Saturday mornings".`),
rd(R1,`Why does the writer not do sport on Sundays?`,[`He is tired`,`He has homework`,`It is boring`,`He goes to the cinema`],`"Porque estoy cansado" means "because I am tired".`),
rd(R1,`Who does the writer go to the cinema with?`,[`friends`,`his father`,`his brother`,`nobody`],`"Con mis amigos" means "with my friends".`))],
/* Very Difficult */[
one(rd(R2,`Why did the writer change sport?`,[`He broke his leg`,`He found football boring`,`His brother told him to`,`Swimming is cheaper`],`"Me rompí la pierna" means "I broke my leg".`),
rd(R2,`What does the writer's brother think?`,[`Football is more exciting`,`Swimming is better for your health`,`Football is dangerous`,`Swimming is boring`],`"Mi hermano dice que el fútbol es más emocionante".`),
rd(R2,`What does "jugaba" tell you?`,[`He used to play (in the past)`,`He plays now`,`He will play`,`He would like to play`],`"Jugaba" is the imperfect tense, used for what someone used to do.`)),
one(tS(`Last weekend I went to the cinema and then I played video games.`,[` fui `,` cine `,` jugue `,` videojuegos `],`El fin de semana pasado fui al cine y luego jugué a los videojuegos.`),
tS(`I used to play tennis, but now I prefer cycling.`,[` jugaba `,` tenis `,` ahora `,` prefiero `,` ciclismo `],`Antes jugaba al tenis, pero ahora prefiero el ciclismo.`),
tS(`Next Saturday I am going to play the guitar in a concert.`,[` voy a tocar `,` guitarra `,` concierto `],`El sábado que viene voy a tocar la guitarra en un concierto.`)),
one(wr(`Write a sentence in Spanish saying what you like to do in your free time and why.`,[ES.OP,ES.BC],`En mi tiempo libre me gusta leer porque es relajante.`),
wr(`Write a sentence in Spanish saying what you did last weekend.`,[ES.PT],`El fin de semana pasado fui al parque y jugué al fútbol con mis amigos.`),
wr(`Write a sentence in Spanish saying what you are going to do next weekend.`,[ES.FT],`El fin de semana que viene voy a ir al cine con mi familia.`)),
conj('pret',[0,2,4,6])]]})();
