/* Spanish: Spanish grammar. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj,mcConj}=ES,
W1=[['y','and'],['pero','but'],['porque','because'],['también','also',,' also | too | as well '],['o','or'],['con','with'],['sin','without'],['muy','very'],['más','more'],['menos','less',,' less | fewer | minus ']],
W2=[['¿Quién?','Who?',' quien ',' who '],['¿Qué?','What?',' que ',' what '],['¿Dónde?','Where?',' donde ',' where '],['¿Cuándo?','When?',' cuando ',' when '],['¿Por qué?','Why?',' por que ',' why '],['¿Cómo?','How?',' como ',' how '],['¿Cuántos?','How many?',' cuantos | cuantas ',' how many '],['¿Cuál?','Which?',' cual ',' which | which one | what ']];
BANK.Spanish['Spanish grammar']=[
/* Easy */[mcEn(W1),toEn(W1),mcConj('pres'),
one(()=>M(`Which word means "the" before a masculine singular noun, such as "libro"?`,[`el`,`la`,`los`,`las`],`el (masculine singular), la (feminine singular), los (masculine plural), las (feminine plural).`),
()=>M(`Which word means "the" before a feminine plural noun, such as "casas"?`,[`las`,`los`,`la`,`el`],`"Casas" is feminine and plural.`),
()=>M(`Choose the correct word: "un gato ______" (a black cat).`,[`negro`,`negra`,`negros`,`negras`],`The adjective agrees with "gato" (masculine singular) and comes after the noun.`),
()=>M(`Choose the correct word: "dos casas ______" (two white houses).`,[`blancas`,`blanco`,`blanca`,`blancos`],`The adjective agrees with "casas" (feminine plural).`))],
/* Moderate */[conj('pres',[0,1,2,3,4,6]),mcEn(W2),toEn(W2),
one(()=>M(`Choose the correct verb: "Yo ______ español." (I am Spanish.)`,[`soy`,`estoy`,`tengo`,`hay`],`"Ser" is used for nationality and permanent characteristics.`),
()=>M(`Choose the correct verb: "Madrid ______ en España." (Madrid is in Spain.)`,[`está`,`es`,`hay`,`tiene`],`"Estar" is used for location.`),
()=>M(`Choose the correct verb: "Hoy ______ cansado." (Today I am tired.)`,[`estoy`,`soy`,`tengo`,`hago`],`"Estar" is used for temporary states and feelings.`)),
one(()=>M(`Choose the correct word: "______ gustan los perros." (I like dogs.)`,[`Me`,`Yo`,`Mi`,`Mis`],`"Me gustan" is used with plural nouns.`),
()=>M(`Which is the correct word for "my" in "______ hermanos" (my brothers)?`,[`mis`,`mi`,`me`,`yo`],`"Mis" is used before a plural noun.`),
()=>M(`How do you make this sentence negative: "Tengo un perro"?`,[`No tengo un perro`,`Tengo no un perro`,`Tengo un no perro`,`Tengo un perro no`],`"No" goes directly before the verb.`))],
/* Difficult */[conj('pret',[0,1,2,3,4,6]),conj('near',[0,1,2,4,6]),mcConj('pret'),
one(()=>M(`"Fui" is the preterite "I" form of which TWO verbs?`,[`ir and ser`,`ir and estar`,`ser and estar`,`tener and hacer`],`"Fui" can mean "I went" or "I was". The context tells you which.`),
()=>M(`Which is the correct preterite form: "Ayer yo ______ los deberes." (hacer)`,[`hice`,`hací`,`hago`,`haré`],`"Hacer" is irregular in the preterite: hice, hiciste, hizo…`),
()=>M(`Which is the correct preterite form: "El año pasado nosotros ______ un coche." (tener)`,[`tuvimos`,`tenimos`,`tenemos`,`tendremos`],`"Tener" is irregular in the preterite: tuve, tuviste, tuvo, tuvimos…`)),
one(()=>M(`Choose the correct pronoun to replace "el libro": "______ compro." (I buy it.)`,[`Lo`,`La`,`Le`,`Los`],`"Lo" replaces a masculine singular noun.`),
()=>M(`Choose the correct comparative: "Madrid es ______ grande ______ Sevilla." (bigger than)`,[`más … que`,`más … de`,`muy … que`,`tan … que`],`"Más + adjective + que" means "more … than".`),
()=>M(`Which connective means "although"?`,[`aunque`,`porque`,`además`,`entonces`],`"Aunque" introduces a contrast.`))],
/* Very Difficult */[conj('fut',[0,1,2,3,4,5,6]),conj('pret',[0,1,2,3,4,5,6,7]),mcConj('fut'),
one(()=>M(`Which tense is used in "Cuando era pequeño, jugaba en el parque"?`,[`imperfect`,`preterite`,`present`,`future`],`The imperfect describes what used to happen or what things were like.`),
()=>M(`Choose the correct form: "Ayer ______ al cine y la película ______ muy larga."`,[`fui … era`,`iba … fue`,`voy … es`,`iré … será`],`The preterite ("fui") is for a completed action; the imperfect ("era") describes what something was like.`),
()=>M(`Which sentence is in the conditional?`,[`Me gustaría vivir en España`,`Me gusta vivir en España`,`Viví en España`,`Viviré en España`],`"Gustaría" means "would like".`)),
one(tS(`I went to the park, I played football and then I ate a sandwich.`,[` fui `,` jugue `,` comi `],`Fui al parque, jugué al fútbol y luego comí un bocadillo.`),
tS(`Tomorrow we are going to visit my grandparents and we will eat together.`,[` vamos a visitar `,` abuelos `,` comeremos | vamos a comer `],`Mañana vamos a visitar a mis abuelos y comeremos juntos.`),
tS(`She is taller than her brother, but less talkative.`,[` mas alta que `,` hermano `,` menos habladora `],`Es más alta que su hermano, pero menos habladora.`))]]})();
