/* Spanish: Home & community. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['la casa','house',,' house | home '],['el piso','flat',,' flat | apartment '],['el dormitorio','bedroom'],['la cocina','kitchen'],['el salón','living room',,' living room | lounge | sitting room '],['el jardín','garden'],['el cuarto de baño','bathroom',' bano '],['la ciudad','city',,' city | town '],['el pueblo','village',,' village | small town | town '],['el barrio','neighbourhood',,' neighbourhood | neighborhood | area | district ']],
W2=[['la tienda','shop',,' shop | store '],['el parque','park'],['la piscina','swimming pool',,' swimming pool | pool '],['el supermercado','supermarket'],['la iglesia','church'],['el museo','museum'],['la estación','station'],['el polideportivo','sports centre',,' sports centre | sports center | leisure centre | leisure center '],['el centro comercial','shopping centre',,' shopping centre | shopping center | mall '],['el mercado','market']],
W3=[['a la derecha','on the right',,' right '],['a la izquierda','on the left',,' left '],['todo recto','straight on',,' straight on | straight ahead | straight '],['cerca de','near',,' near | close to | nearby '],['lejos de','far from',,' far '],['al lado de','next to',,' next to | beside | by the side '],['enfrente de','opposite',,' opposite | in front of | facing '],['hay','there is',,' there is | there are '],['tranquilo','quiet',' tranquil',' quiet | calm | peaceful '],['ruidoso','noisy',' ruidos']],
R1=`Vivo en un piso pequeño en el centro de Valencia. En mi barrio hay muchas tiendas y un parque grande, pero no hay piscina. Me gusta mi barrio porque es animado, aunque es un poco ruidoso.`,
R2=`Antes vivíamos en un pueblo tranquilo en el campo, donde no había nada que hacer para los jóvenes. Hace dos años nos mudamos a la ciudad. Ahora tengo el polideportivo a cinco minutos de casa, pero echo de menos el jardín que teníamos.`;
BANK.Spanish['Home & community']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W2),mcEn(W2)],
/* Moderate */[toEs(W1),toEn(W2),mcEn(W3),
one(tE(`Vivo en una casa grande con jardín.`,[`live`,`big|large`,`house`,`garden`],`I live in a big house with a garden.`),
tE(`En mi pueblo hay un parque y una iglesia.`,[`village|town`,`park`,`church`],`In my village there is a park and a church.`),
tE(`El museo está cerca de la estación.`,[`museum`,`near|close`,`station`],`The museum is near the station.`)),
one(()=>M(`Choose the correct word: "En mi ciudad ______ muchas tiendas."`,[`hay`,`es`,`está`,`son`],`"Hay" means "there is" or "there are".`),
()=>M(`Choose the correct word: "La piscina ______ al lado del parque."`,[`está`,`es`,`hay`,`tiene`],`"Estar" is used to say where something is.`),
()=>M(`"Toma la primera calle a la izquierda" means…`,[`Take the first street on the left`,`Take the first street on the right`,`Go straight on`,`Cross the first street`],`"A la izquierda" means "on the left".`))],
/* Difficult */[toEs(W2),toEs(W3),
one(tS(`My bedroom is small but comfortable.`,[` dormitorio | habitacion `,` pequen`,` pero `,` comod`],`Mi dormitorio es pequeño pero cómodo.`),
tS(`The supermarket is opposite the park.`,[` supermercado `,` esta `,` enfrente `,` parque `],`El supermercado está enfrente del parque.`),
tS(`In my town there is a swimming pool but there is no museum.`,[` hay `,` piscina `,` pero `,` no hay `,` museo `],`En mi ciudad hay una piscina pero no hay museo.`)),
one(rd(R1,`Where does the writer live?`,[`in a small flat in the city centre`,`in a big house in a village`,`in a flat near the beach`,`in a house with a garden`],`"Un piso pequeño en el centro" means "a small flat in the centre".`),
rd(R1,`What is missing from the neighbourhood?`,[`a swimming pool`,`shops`,`a park`,`a market`],`"No hay piscina" means "there is no swimming pool".`),
rd(R1,`What is the disadvantage of the neighbourhood?`,[`It is a bit noisy`,`It is boring`,`It is far from the centre`,`It is dirty`],`"Un poco ruidoso" means "a bit noisy".`))],
/* Very Difficult */[
one(rd(R2,`What was the problem with the village?`,[`There was nothing for young people to do`,`It was too noisy`,`It was too far from school`,`The house was too small`],`"No había nada que hacer para los jóvenes".`),
rd(R2,`When did the family move?`,[`two years ago`,`five minutes ago`,`last year`,`two months ago`],`"Hace dos años" means "two years ago".`),
rd(R2,`What does the writer miss?`,[`the garden`,`the sports centre`,`the countryside walks`,`the old school`],`"Echo de menos el jardín" means "I miss the garden".`)),
one(tS(`I used to live in a village, but now I live in a city.`,[` vivia `,` pueblo `,` ahora `,` vivo `,` ciudad `],`Antes vivía en un pueblo, pero ahora vivo en una ciudad.`),
tS(`Go straight on and take the second street on the right.`,[` todo recto `,` segunda calle `,` derecha `],`Sigue todo recto y toma la segunda calle a la derecha.`),
tS(`If I were rich, I would buy a house with a swimming pool.`,[` si `,` fuera `,` ric`,` compraria `,` casa `,` piscina `],`Si fuera rico, compraría una casa con piscina.`)),
one(wr(`Write a sentence in Spanish describing your town or village: say what there is and what there is not.`,[` hay `,` no hay | pero | sin embargo `],`En mi ciudad hay un cine y muchas tiendas, pero no hay playa.`),
wr(`Write a sentence in Spanish giving your opinion of where you live, with a reason.`,[ES.OP+`| es `,ES.BC],`Me gusta mi barrio porque es tranquilo y hay un parque cerca.`),
wr(`Write directions in Spanish from your house to a shop, using at least one of: "a la derecha", "a la izquierda", "todo recto".`,[` a la derecha | a la izquierda | todo recto `],`Sal de mi casa, sigue todo recto y la tienda está a la izquierda.`)),
conj('pres',[0,2,4,5,6])]]})();
