/* Spanish: Me, myself & identity. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['el hermano','brother'],['la hermana','sister'],['el padre','father',,' father | dad '],['la madre','mother',,' mother | mum | mom '],['el abuelo','grandfather',,' grandfather | grandad | granddad | grandpa '],['la abuela','grandmother',,' grandmother | grandma | granny | gran | nan '],['el tío','uncle'],['la tía','aunt',,' aunt | auntie | aunty '],['el primo','cousin'],['el amigo','friend']],
W2=[['simpático','nice',' simpatic',' nice | kind | friendly '],['perezoso','lazy',' perezos'],['trabajador','hard-working',' trabajador',' hard-working | hardworking | hard working '],['divertido','fun',' divertid',' fun | funny | amusing | entertaining '],['tímido','shy',' timid'],['alto','tall',' alt'],['bajo','short',' baj'],['inteligente','intelligent',,' intelligent | clever | smart '],['hablador','talkative',' hablador',' talkative | chatty '],['generoso','generous',' generos']],
W3=[['me llamo','my name is',,' my name is | i am called | i m called '],['vivo en','I live in'],['mi cumpleaños','my birthday',' cumpleanos ',' birthday '],['me llevo bien con','I get on well with',,' get on well | get along '],['tengo los ojos azules','I have blue eyes',' ojos azules ',' blue eyes '],['tengo el pelo corto','I have short hair',' pelo corto ',' short hair '],['soy hijo único','I am an only child',' hijo unico | hija unica ',' only child '],['mi mejor amigo','my best friend',' mejor amig',' best friend ']],
R1=`Hola, me llamo Lucía y tengo catorce años. Vivo en Sevilla con mis padres y mi hermano menor, Pablo. Pablo tiene diez años y es muy hablador.`,
R2=`Me llamo Diego. Mi hermana mayor, Carla, tiene dieciocho años; yo tengo cinco años menos que ella. Nuestro primo Luis tiene la misma edad que yo, pero es más alto.`;
BANK.Spanish['Me, myself & identity']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),
one(()=>M(`"Me llamo Ana" means…`,[`My name is Ana`,`I am calling Ana`,`I like Ana`,`Ana is my friend`],`"Me llamo" literally means "I call myself".`),
()=>M(`"Tengo doce años" means…`,[`I am twelve years old`,`I have twelve brothers`,`It is twelve o'clock`,`I live at number twelve`],`Spanish uses "tener" (to have) for age: "I have twelve years".`),
()=>M(`How do you ask "What is your name?" in Spanish?`,[`¿Cómo te llamas?`,`¿Cuántos años tienes?`,`¿Dónde vives?`,`¿Qué tal?`],`"¿Cómo te llamas?" literally means "What do you call yourself?"`))],
/* Moderate */[toEs(W1),mcEn(W2),toEn(W2),
one(tE(`Tengo dos hermanos y una hermana.`,[`two brother`,`sister`],`I have two brothers and one sister.`),
tE(`Mi madre es alta y muy simpática.`,[`mother|mum|mom`,`tall`,`nice|kind|friendly`],`My mother is tall and very nice.`),
tE(`Vivo en Londres con mi familia.`,[`live`,`london`,`family`],`I live in London with my family.`)),
one(()=>M(`Choose the correct word: "Mi hermana es ______."`,[`alta`,`alto`,`altos`,`altas`],`The adjective must be feminine and singular to agree with "hermana".`),
()=>M(`Choose the correct word: "Mis padres son ______."`,[`simpáticos`,`simpático`,`simpática`,`simpáticas`],`The adjective must be masculine and plural to agree with "padres".`),
()=>M(`Choose the correct word: "Yo ______ trece años."`,[`tengo`,`soy`,`estoy`,`hay`],`Spanish uses "tener" for age.`))],
/* Difficult */[toEs(W2),toEs(W3),
one(tS(`I have a brother who is called Juan.`,[` tengo `,` hermano `,` se llama `],`Tengo un hermano que se llama Juan.`),
tS(`My best friend is funny and hard-working.`,[` mejor amig`,` divertid`,` trabajador`],`Mi mejor amigo es divertido y trabajador.`),
tS(`I get on well with my sister because she is nice.`,[` me llevo bien `,` hermana `,` porque `,` simpatica `],`Me llevo bien con mi hermana porque es simpática.`)),
one(rd(R1,`How old is Lucía's brother?`,[`10`,`14`,`13`,`12`],`"Pablo tiene diez años" means "Pablo is ten".`),
rd(R1,`Where does Lucía live?`,[`Seville`,`Madrid`,`London`,`Barcelona`],`"Vivo en Sevilla" means "I live in Seville".`),
rd(R1,`What is Pablo like?`,[`very talkative`,`very shy`,`very lazy`,`very tall`],`"Hablador" means talkative.`))],
/* Very Difficult */[
one(rd(R2,`How old is Diego?`,[`13`,`18`,`23`,`5`],`Carla is 18 and Diego is five years younger ("cinco años menos"): 18 − 5 = 13.`),
rd(R2,`Who is taller, Diego or Luis?`,[`Luis`,`Diego`,`They are the same height`,`The text does not say`],`"Es más alto" means "he is taller", and it refers to Luis.`),
rd(R2,`How is Luis related to Carla?`,[`He is her cousin`,`He is her brother`,`He is her uncle`,`He is her friend`],`"Nuestro primo" means "our cousin".`)),
one(tS(`When I was younger I was shy, but now I am talkative.`,[` era `,` timid`,` ahora `,` hablador`],`Cuando era más joven era tímido, pero ahora soy hablador.`),
tS(`My parents are generous, although they are sometimes strict.`,[` padres `,` generosos `,` aunque `,` estrictos `],`Mis padres son generosos, aunque a veces son estrictos.`),
tS(`I would like to have a dog because I am an only child.`,[` me gustaria | quisiera `,` perro `,` porque `,` hijo unico | hija unica `],`Me gustaría tener un perro porque soy hijo único.`)),
one(wr(`Write a sentence in Spanish describing a member of your family: say who they are and what they are like, and give a reason for your opinion of them.`,[` mi `,` es `,ES.BC],`Mi hermano es muy divertido y me llevo bien con él porque es simpático.`),
wr(`Write a sentence in Spanish introducing yourself: give your name, your age and where you live.`,[` me llamo | soy `,` tengo `,` anos `,` vivo `],`Me llamo Sam, tengo trece años y vivo en Londres.`),
wr(`Write a sentence in Spanish describing your best friend's personality, using two adjectives joined by "y" or "pero".`,[` amig`,` es `,` y | pero `],`Mi mejor amiga es inteligente y habladora, pero un poco perezosa.`)),
conj('pres',[0,2,4,6])]]})();
