/* Spanish: Practical language skills. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['me gusta','I like'],['no me gusta','I do not like',,' don t like | do not like | dislike '],['me encanta','I love',,' i love | i really like '],['odio','I hate'],['prefiero','I prefer'],['es divertido','it is fun',' es divertid',' fun | funny | enjoyable '],['es aburrido','it is boring',' es aburrid',' boring '],['es genial','it is great',,' great | brilliant | fantastic | cool '],['creo que','I think that',,' i think | i believe '],['en mi opinión','in my opinion',,' in my opinion ']],
W2=[['porque','because'],['pero','but'],['también','also',,' also | too | as well '],['sin embargo','however',,' however | nevertheless '],['por ejemplo','for example',,' for example | for instance '],['además','moreover',,' moreover | furthermore | also | in addition | besides '],['aunque','although',,' although | even though | though '],['por eso','that is why',,' that is why | that s why | so | therefore | for that reason '],['primero','first',,' first | firstly '],['luego','then',,' then | next | later | afterwards ']],
rp=(sit,kw,a,o)=>()=>T(`Role-play. ${sit} Write what you would say in Spanish.`,kw,a,`Your reply is checked only for the key words. Compare the rest with the model answer yourself.`,o);
BANK.Spanish['Practical language skills']=[
/* Easy */[mcEn(W1),toEn(W1),toEs(W1),
one(()=>M(`A new classmate says "¿Cómo te llamas?". Which is a suitable reply?`,[`Me llamo Sam.`,`Tengo trece años.`,`Vivo en Londres.`,`Muy bien, gracias.`],`The question asks for your name.`),
()=>M(`A waiter says "¿Qué quieres beber?". Which is a suitable reply?`,[`Un zumo de naranja, por favor.`,`Una pizza, por favor.`,`Me llamo Ana.`,`Son las tres.`],`"Beber" means "to drink", so you should name a drink.`),
()=>M(`Someone says "Gracias". Which is the usual reply?`,[`De nada.`,`Por favor.`,`Lo siento.`,`Hola.`],`"De nada" means "you're welcome".`),
()=>M(`A friend asks "¿Qué tal?". Which is a suitable reply?`,[`Muy bien, ¿y tú?`,`Tengo doce años.`,`A las ocho.`,`En el parque.`],`"¿Qué tal?" means "How are you?"`))],
/* Moderate */[mcEn(W2),toEn(W2),
one(rp(`In a café, the waiter asks: "¿Qué quieres comer?"`,[` quiero | quisiera | me gustaria | para mi | un | una `],`Quisiera un bocadillo de queso, por favor.`),
rp(`A Spanish visitor asks you: "¿Dónde vives?"`,[` vivo `],`Vivo en Londres, en Inglaterra.`),
rp(`Your pen friend asks: "¿Cuántos años tienes?"`,[` tengo `,` anos `],`Tengo trece años.`),
rp(`A shop assistant asks: "¿Qué desea?" You want to buy a T-shirt.`,[` camiseta `],`Quisiera una camiseta, por favor.`)),
one(wr(`Write a sentence in Spanish giving your opinion of sport.`,[ES.OP+`| es `],`Me encanta el deporte porque es divertido.`),
wr(`Write a sentence in Spanish giving your opinion of your town.`,[ES.OP+`| es `],`Me gusta mi ciudad porque hay muchas tiendas.`),
wr(`Write a sentence in Spanish giving your opinion of school uniform.`,[ES.OP+`| es `],`No me gusta el uniforme porque es feo.`)),
one(tE(`Me gusta el fútbol, pero prefiero el tenis.`,[`like`,`football|soccer`,`but`,`prefer`,`tennis`],`I like football, but I prefer tennis.`),
tE(`Creo que la música es genial.`,[`think|believe`,`music`,`great|brilliant|fantastic|cool`],`I think that music is great.`),
tE(`Odio los lunes porque tengo matemáticas.`,[`hate`,`monday`,`because`,`math`],`I hate Mondays because I have maths.`))],
/* Difficult */[toEs(W2),
one(wr(`Write a sentence in Spanish giving an opinion AND a reason about your favourite hobby.`,[ES.OP,ES.BC],`Me encanta la natación porque es relajante y sana.`),
wr(`Write a sentence in Spanish giving an opinion AND a reason about a school subject you dislike.`,[` no me gusta| odio | detesto | no me interesa`,ES.BC],`No me gusta la geografía porque es aburrida.`),
wr(`Write a sentence in Spanish giving an opinion AND a reason about a film or book.`,[ES.OP+`| fue | es `,ES.BC],`Me gustó la película porque fue muy emocionante.`)),
one(wr(`Describe your bedroom in one Spanish sentence, using "hay" and at least one adjective.`,[` hay `,` dormitorio | habitacion | cuarto | cama | mesa | armario `],`En mi dormitorio hay una cama grande y una mesa pequeña.`),
wr(`Describe a friend in one Spanish sentence: mention their appearance and their personality.`,[` es `,` tiene | alto| baj| pelo | ojos `],`Mi amigo Tom es alto y simpático, y tiene el pelo corto.`),
wr(`Describe your school in one Spanish sentence, using "es" and "hay".`,[` es `,` hay `],`Mi colegio es grande y moderno, y hay un polideportivo.`)),
one(rp(`At a train station, you want a return ticket to Madrid.`,[` billete `,` madrid `],`Quisiera un billete de ida y vuelta a Madrid, por favor.`),
rp(`In a restaurant, the food is cold. Complain politely to the waiter.`,[` fria | frio `,` comida | sopa | plato | pollo | carne | pescado | esta `],`Perdone, la comida está fría.`),
rp(`You are lost. Ask a passer-by where the station is.`,[` donde esta `,` estacion `],`Perdone, ¿dónde está la estación?`)),
conj('pres',[0,1,2,4,6])],
/* Very Difficult */[
one(wr(`Write TWO linked ideas in Spanish about your weekend: one thing you did (past) and one thing you are going to do (future).`,[ES.PT,ES.FT],`El sábado fui al cine con mis amigos y mañana voy a jugar al fútbol.`),
wr(`Write in Spanish what you usually do after school (present) and what you did yesterday (past).`,[` normalmente | generalmente | siempre | a menudo | todos los dias | suelo | despues `,ES.PT+`| ayer `],`Normalmente hago mis deberes, pero ayer fui a la piscina.`),
wr(`Write in Spanish about your town: what it is like now and what you would change, using "me gustaría" or the conditional.`,[` es | hay `,` me gustaria | quisiera | cambiaria | construiria | habria | seria `],`Mi ciudad es pequeña y aburrida; me gustaría tener un cine.`)),
one(wr(`Give your opinion of homework in Spanish, with a reason AND a contrasting idea using "pero", "aunque" or "sin embargo".`,[ES.OP+`| son | es `,ES.BC,` pero | aunque | sin embargo `],`No me gustan los deberes porque son aburridos; sin embargo, son útiles.`),
wr(`Compare two hobbies in Spanish using "más … que" or "menos … que", and say which you prefer.`,[` mas | menos `,` que `,` prefiero | me gusta mas | me encanta `],`El tenis es más emocionante que la natación, pero prefiero nadar.`),
wr(`Justify in Spanish why learning languages is important, using "porque" and one other connective.`,[ES.BC,` ademas | tambien | pero | aunque | sin embargo | por eso | por ejemplo | y `],`Es importante aprender idiomas porque son útiles para viajar; además, es divertido.`)),
one(rp(`You are booking a hotel room by phone. Ask for a room for two nights with a sea view.`,[` habitacion `,` dos noches `,` mar `],`Quisiera una habitación para dos noches con vista al mar, por favor.`),
rp(`At the doctor's, explain that you have had a headache since yesterday.`,[` duele la cabeza | dolor de cabeza `,` ayer `],`Me duele la cabeza desde ayer.`),
rp(`You bought trainers that are too small. Ask the shop assistant to exchange them for a bigger size.`,[` zapatillas `,` pequenas `,` cambiar`],`Compré estas zapatillas pero son demasiado pequeñas. ¿Puedo cambiarlas por una talla más grande?`)),
one(tS(`First I do my homework, then I watch TV and afterwards I go to bed.`,[` primero `,` deberes `,` luego | despues `,` veo la tele`,` cama | acuesto `],`Primero hago mis deberes, luego veo la tele y después me voy a la cama.`),
tS(`I think the film was good; however, the book is better.`,[` creo que | pienso que | en mi opinion `,` pelicula `,` sin embargo | pero `,` libro `,` mejor `],`Creo que la película fue buena; sin embargo, el libro es mejor.`),
tS(`Although it was raining, we went to the beach and we had a great time.`,[` aunque `,` llovia `,` fuimos `,` playa `,` lo pasamos `],`Aunque llovía, fuimos a la playa y lo pasamos genial.`))]]})();
