/* Spanish: School & education. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['las matemáticas','maths',,' maths | math | mathematics '],['el inglés','English'],['la historia','history'],['las ciencias','science',,' science | sciences '],['el dibujo','art',,' art | drawing '],['la geografía','geography'],['la educación física','PE',,' pe | p.e. | physical education '],['la informática','ICT',,' ict | it | computing | computer science '],['el español','Spanish'],['la música','music']],
W2=[['el profesor','teacher'],['los deberes','homework'],['el recreo','break',,' break | breaktime | break time | recess | playtime '],['el uniforme','uniform'],['la clase','lesson',,' lesson | class | classroom '],['el colegio','school'],['el horario','timetable',,' timetable | schedule '],['la biblioteca','library'],['el examen','exam',,' exam | test | examination '],['el alumno','pupil',,' pupil | student ']],
W3=[['difícil','difficult',,' difficult | hard '],['fácil','easy'],['útil','useful'],['aburrido','boring',' aburrid'],['interesante','interesting'],['estricto','strict',' estrict'],['hay que','you have to',,' have to | must | it is necessary '],['no se permite','it is not allowed',' no se permite ',' not allowed | not permitted | forbidden | mustn t | must not | can t | cannot '],['las reglas','rules'],['empieza a las nueve','it starts at nine',' empieza a las nueve ',' starts at nine | begins at nine | starts at 9 | begins at 9 ']],
R1=`Mi colegio es grande y moderno. Las clases empiezan a las nueve menos cuarto y terminan a las tres y media. Mi asignatura favorita es la historia porque el profesor es divertido, pero no me gustan las matemáticas.`,
R2=`En mi colegio hay muchas reglas. No se permite usar el móvil en clase y hay que llevar uniforme, que es bastante feo. Lo bueno es que hay muchos clubes después de las clases; lo malo es que tenemos demasiados deberes.`;
BANK.Spanish['School & education']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W2),
one(()=>M(`"Mi asignatura favorita es el inglés" means…`,[`My favourite subject is English`,`My teacher is English`,`I study English every day`,`I am good at English`],`"Asignatura" means "school subject".`),
()=>M(`"Me gusta la historia" means…`,[`I like history`,`I hate history`,`I study history`,`History is boring`],`"Me gusta" means "I like".`),
()=>M(`Which word means "homework"?`,[`los deberes`,`el recreo`,`el horario`,`la clase`],`"Hago mis deberes" means "I do my homework".`))],
/* Moderate */[toEs(W1),toEn(W2),mcEn(W3),
one(tE(`Estudio ciencias los lunes y los jueves.`,[`study`,`science`,`monday`,`thursday`],`I study science on Mondays and Thursdays.`),
tE(`El profesor de geografía es muy estricto.`,[`geography`,`teacher`,`strict`],`The geography teacher is very strict.`),
tE(`No me gustan las matemáticas porque son difíciles.`,[`don t like|do not like|dislike`,`math`,`difficult|hard`],`I don't like maths because it is difficult.`)),
one(()=>M(`Choose the correct word: "Las ciencias ______ interesantes."`,[`son`,`es`,`soy`,`eres`],`"Las ciencias" is plural, so the verb is "son".`),
()=>M(`Choose the correct word: "______ gusta el dibujo."`,[`Me`,`Yo`,`Mi`,`Soy`],`"Me gusta" means "I like" (literally "it pleases me").`),
()=>M(`"Las clases empiezan a las ocho y media" means that lessons start at…`,[`8:30`,`8:15`,`7:30`,`8:00`],`"Y media" means "half past".`))],
/* Difficult */[toEs(W2),toEs(W3),
one(tS(`My favourite subject is science because it is interesting.`,[` asignatura favorita `,` ciencias `,` porque `,` interesante`],`Mi asignatura favorita son las ciencias porque son interesantes.`),
tS(`We have to wear a uniform.`,[` hay que | tenemos que `,` llevar `,` uniforme `],`Hay que llevar uniforme.`),
tS(`Yesterday I studied history in the library.`,[` ayer `,` estudie `,` historia `,` biblioteca `],`Ayer estudié historia en la biblioteca.`)),
one(rd(R1,`At what time do lessons start?`,[`8:45`,`9:15`,`9:00`,`3:30`],`"Las nueve menos cuarto" means "quarter to nine".`),
rd(R1,`Why does the writer like history?`,[`The teacher is fun`,`It is easy`,`It is useful`,`There is no homework`],`"Porque el profesor es divertido" means "because the teacher is fun".`),
rd(R1,`Which subject does the writer dislike?`,[`maths`,`history`,`science`,`English`],`"No me gustan las matemáticas" means "I don't like maths".`))],
/* Very Difficult */[
one(rd(R2,`What is NOT allowed in class?`,[`using a mobile phone`,`wearing uniform`,`joining clubs`,`doing homework`],`"No se permite usar el móvil" means "using a mobile is not allowed".`),
rd(R2,`What does the writer think of the uniform?`,[`It is quite ugly`,`It is comfortable`,`It is expensive`,`It is smart`],`"Bastante feo" means "quite ugly".`),
rd(R2,`What is the bad thing about the school, according to the writer?`,[`There is too much homework`,`There are too many clubs`,`There are too many rules`,`The lessons are too long`],`"Lo malo es que tenemos demasiados deberes": the bad thing is that we have too much homework.`)),
one(tS(`Last year I used to study French, but now I study Spanish.`,[` estudiaba `,` frances `,` ahora `,` estudio `,` espanol `],`El año pasado estudiaba francés, pero ahora estudio español.`),
tS(`If I had more time, I would do more sport at school.`,[` si `,` tuviera `,` tiempo `,` haria `,` deporte `],`Si tuviera más tiempo, haría más deporte en el colegio.`),
tS(`Using a mobile phone in class is not allowed.`,[` no se permite | esta prohibido | no se puede `,` movil `,` clase `],`No se permite usar el móvil en clase.`)),
one(wr(`Write a sentence in Spanish giving your opinion of a school subject, with a reason.`,[ES.OP,ES.BC],`Me encanta el español porque es útil y el profesor es simpático.`),
wr(`Write a sentence in Spanish describing one rule at your school, using "hay que" or "no se permite".`,[` hay que | no se permite | no se puede | esta prohibido | tenemos que `],`En mi colegio hay que llevar uniforme y no se permite comer chicle.`),
wr(`Write a sentence in Spanish saying what you studied yesterday at school.`,[` ayer `,` estudie | tuve | hice | aprendi `],`Ayer estudié matemáticas e inglés, y tuve un examen de ciencias.`)),
ES.mcConj('pres')]]})();
