/* Spanish: Young people & society. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['el móvil','mobile phone',,' mobile | phone | cell | mobile phone '],['el ordenador','computer'],['las redes sociales','social media',' redes sociales ',' social media | social networks '],['los jóvenes','young people',,' young people | youth | youngsters | teenagers '],['el dinero','money'],['la ropa','clothes',,' clothes | clothing '],['la moda','fashion'],['el amigo','friend'],['la pantalla','screen'],['el mensaje','message',,' message | text ']],
W2=[['ayudar','to help'],['compartir','to share'],['el voluntario','volunteer'],['la paga','pocket money',,' pocket money | allowance '],['las tareas domésticas','household chores',' tareas domesticas ',' chores | housework | household tasks | jobs around the house '],['el acoso','bullying',,' bullying | harassment '],['la presión','pressure'],['el estrés','stress'],['la libertad','freedom',,' freedom | liberty '],['los derechos','rights']],
W3=[['estoy de acuerdo','I agree',' de acuerdo ',' i agree | agree '],['no estoy de acuerdo','I disagree',' no estoy de acuerdo ',' disagree | don t agree | do not agree '],['por un lado','on the one hand',,' on the one hand | on one hand '],['por otro lado','on the other hand',,' on the other hand '],['sin embargo','however',,' however | nevertheless '],['además','also',,' also | moreover | furthermore | in addition | besides '],['peligroso','dangerous',' peligros'],['útil','useful'],['adicto','addicted',' adict',' addicted | addict '],['una ventaja','an advantage',' ventaja ',' advantage ']],
R1=`Uso mi móvil todos los días para hablar con mis amigos y escuchar música. Mis padres dicen que paso demasiado tiempo delante de la pantalla. Recibo diez euros de paga a la semana si ayudo en casa.`,
R2=`Las redes sociales tienen ventajas y desventajas. Por un lado, son útiles para compartir fotos y estar en contacto con los amigos que viven lejos. Por otro lado, pueden ser peligrosas porque algunos jóvenes sufren acoso en línea. En mi opinión, lo importante es no pasar más de una hora al día conectado.`;
BANK.Spanish['Young people & society']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),mcEn(W2)],
/* Moderate */[toEs(W1),toEn(W2),mcEn(W3),
one(tE(`Uso mi móvil para mandar mensajes.`,[`use`,`mobile|phone`,`send`,`message|text`],`I use my mobile to send messages.`),
tE(`Ayudo en casa todos los fines de semana.`,[`help`,`home|house`,`weekend`],`I help at home every weekend.`),
tE(`Los jóvenes pasan mucho tiempo en las redes sociales.`,[`young|teenager|youth`,`time`,`social`],`Young people spend a lot of time on social media.`)),
one(()=>M(`"Estoy de acuerdo" means…`,[`I agree`,`I remember`,`I am ready`,`I am happy`],`"De acuerdo" means "in agreement".`),
()=>M(`Choose the correct word: "Las redes sociales ______ útiles."`,[`son`,`es`,`está`,`hay`],`"Las redes sociales" is plural, so the verb is "son".`),
()=>M(`Which word means "however"?`,[`sin embargo`,`porque`,`también`,`por ejemplo`],`"Sin embargo" introduces a contrasting idea.`))],
/* Difficult */[toEs(W2),toEs(W3),
one(tS(`I receive pocket money if I help at home.`,[` recibo `,` paga | dinero `,` si `,` ayudo `,` casa `],`Recibo paga si ayudo en casa.`),
tS(`Social media is useful but it can be dangerous.`,[` redes sociales `,` utiles `,` pero `,` peligrosas `],`Las redes sociales son útiles pero pueden ser peligrosas.`),
tS(`Yesterday I helped my grandmother with the shopping.`,[` ayer `,` ayude `,` abuela `,` compra`],`Ayer ayudé a mi abuela con la compra.`)),
one(rd(R1,`What does the writer use the mobile phone for?`,[`talking to friends and listening to music`,`doing homework`,`watching films`,`playing games`],`"Para hablar con mis amigos y escuchar música".`),
rd(R1,`What do the writer's parents say?`,[`The writer spends too much time in front of the screen`,`The writer should buy a new phone`,`The writer does not help enough`,`The writer spends too much money`],`"Paso demasiado tiempo delante de la pantalla".`),
rd(R1,`On what condition does the writer receive pocket money?`,[`if the writer helps at home`,`if the writer gets good marks`,`if the writer uses the phone less`,`there is no condition`],`"Si ayudo en casa" means "if I help at home".`))],
/* Very Difficult */[
one(rd(R2,`Which advantage of social media does the text mention?`,[`staying in contact with friends who live far away`,`learning languages`,`finding a job`,`saving money`],`"Estar en contacto con los amigos que viven lejos".`),
rd(R2,`Why can social media be dangerous, according to the text?`,[`Some young people suffer online bullying`,`It costs too much money`,`It damages your eyes`,`It stops you sleeping`],`"Algunos jóvenes sufren acoso en línea".`),
rd(R2,`What does the writer recommend?`,[`spending no more than one hour a day online`,`deleting all social media`,`only sharing photos`,`using social media only at weekends`],`"No pasar más de una hora al día conectado".`)),
one(tS(`On the one hand, mobile phones are useful; on the other hand, they can be dangerous.`,[` por un lado `,` moviles `,` utiles `,` por otro lado `,` peligrosos `],`Por un lado, los móviles son útiles; por otro lado, pueden ser peligrosos.`),
tS(`In my opinion, young people have too much stress.`,[` en mi opinion | creo que | pienso que `,` jovenes `,` demasiado estres `],`En mi opinión, los jóvenes tienen demasiado estrés.`),
tS(`I would like to work as a volunteer to help my community.`,[` me gustaria | quisiera `,` trabajar `,` voluntari`,` ayudar `,` comunidad `],`Me gustaría trabajar como voluntario para ayudar a mi comunidad.`)),
one(wr(`Write a sentence in Spanish giving one advantage and one disadvantage of mobile phones.`,[` ventaja | util| bueno | por un lado | lo bueno `,` desventaja | peligros| malo | por otro lado | pero | sin embargo | lo malo `],`Lo bueno de los móviles es que son útiles, pero lo malo es que son caros.`),
wr(`Write a sentence in Spanish saying how you help at home.`,[` ayudo | hago | lavo | pongo | limpio | cocino | paso | saco | arreglo | plancho `],`Ayudo en casa: pongo la mesa y lavo los platos.`),
wr(`Write a sentence in Spanish giving your opinion about social media, with a reason.`,[ES.OP+`| son `,ES.BC],`Creo que las redes sociales son divertidas porque puedo hablar con mis amigos.`)),
ES.mcConj('pret')]]})();
