/* Spanish: Travel & holidays. BANK.Spanish[topic] = [easy, moderate, difficult, very difficult]. Helpers are in spanish/core.js and subjects.js. */
(()=>{const {toEn,toEs,mcEn,mcEs,tE,tS,rd,wr,conj}=ES,
W1=[['el avión','plane',,' plane | aeroplane | airplane '],['el tren','train'],['el coche','car'],['el barco','boat',,' boat | ship '],['el autobús','bus',,' bus | coach '],['la playa','beach'],['el hotel','hotel'],['la maleta','suitcase',,' suitcase | case '],['el billete','ticket'],['las vacaciones','holidays',,' holiday | holidays | vacation ']],
W2=[['España','Spain'],['Francia','France'],['Alemania','Germany'],['Italia','Italy'],['Inglaterra','England'],['los Estados Unidos','the United States',' estados unidos ',' united states | usa | u.s.a | america '],['el extranjero','abroad'],['la montaña','mountain',,' mountain | mountains '],['el campo','countryside',,' countryside | country '],['la costa','coast',,' coast | seaside ']],
W3=[['fui','I went'],['viajé','I travelled',,' i travelled | i traveled '],['me alojé','I stayed'],['visité','I visited'],['tomé el sol','I sunbathed',' tome el sol ',' sunbathed | sunbathe | sun bathed '],['saqué fotos','I took photos',' saque fotos ',' took photos | took pictures | took photographs '],['lo pasé bien','I had a good time',' lo pase bien ',' good time | great time | had fun | enjoyed '],['hizo sol','it was sunny',,' sunny '],['llovió','it rained',,' rained | rainy '],['el año pasado','last year']],
R1=`El verano pasado fui a Mallorca con mi familia. Viajamos en avión y nos alojamos en un hotel cerca de la playa. Hizo mucho calor, así que nadé en el mar todos los días.`,
R2=`Normalmente vamos de vacaciones a Francia en coche, pero este año iremos a México en avión porque mi tía vive allí. El viaje dura once horas, lo que me parece demasiado largo. Sin embargo, tengo ganas de probar la comida mexicana.`;
BANK.Spanish['Travel & holidays']=[
/* Easy */[mcEn(W1),toEn(W1),mcEs(W1),mcEn(W2)],
/* Moderate */[toEs(W1),toEn(W2),mcEn(W3),
one(tE(`Voy a España en avión.`,[`go|going|travel`,`spain`,`plane`],`I go to Spain by plane.`),
tE(`Prefiero ir a la playa porque me gusta nadar.`,[`prefer`,`beach`,`because`,`swim`],`I prefer to go to the beach because I like swimming.`),
tE(`Nos alojamos en un hotel pequeño.`,[`stay`,`small|little`,`hotel`],`We stay (or stayed) in a small hotel.`)),
one(()=>M(`Choose the correct word: "Voy a Italia ______ tren."`,[`en`,`a`,`por`,`con`],`Spanish uses "en" for means of transport: en tren, en avión, en coche.`),
()=>M(`"Hace buen tiempo" means…`,[`The weather is good`,`It is a good time`,`I have a good time`,`It is early`],`"Hace" is used for many weather expressions.`),
()=>M(`Which phrase means "I went to France"?`,[`Fui a Francia`,`Voy a Francia`,`Iré a Francia`,`Vivo en Francia`],`"Fui" is the preterite (past) of "ir".`))],
/* Difficult */[toEs(W3),toEn(W3),
one(tS(`Last year I went to Spain by plane.`,[` ano pasado `,` fui `,` espana `,` avion `],`El año pasado fui a España en avión.`),
tS(`I stayed in a hotel near the beach.`,[` me aloje | me quede `,` hotel `,` cerca `,` playa `],`Me alojé en un hotel cerca de la playa.`),
tS(`It was sunny and I had a good time.`,[` hizo sol `,` lo pase bien | lo pase genial | me diverti `],`Hizo sol y lo pasé bien.`)),
one(rd(R1,`How did the family travel?`,[`by plane`,`by boat`,`by car`,`by train`],`"Viajamos en avión" means "we travelled by plane".`),
rd(R1,`Where was the hotel?`,[`near the beach`,`in the mountains`,`in the city centre`,`near the airport`],`"Cerca de la playa" means "near the beach".`),
rd(R1,`Why did the writer swim every day?`,[`It was very hot`,`The pool was free`,`It was raining`,`The hotel was boring`],`"Hizo mucho calor, así que…" means "it was very hot, so…".`))],
/* Very Difficult */[
one(rd(R2,`Why is the family going to Mexico this year?`,[`The writer's aunt lives there`,`It is cheaper than France`,`They do not like France`,`They want to travel by car`],`"Porque mi tía vive allí" means "because my aunt lives there".`),
rd(R2,`What does the writer think of the journey?`,[`It is too long`,`It is exciting`,`It is too expensive`,`It is comfortable`],`"Demasiado largo" means "too long".`),
rd(R2,`What is the writer looking forward to?`,[`trying Mexican food`,`the long flight`,`driving to France`,`seeing the beach`],`"Tengo ganas de probar la comida mexicana" means "I am looking forward to trying Mexican food".`)),
one(tS(`Next summer I will go to Italy with my friends.`,[` verano `,` ire | voy a ir `,` italia `,` amigos `],`El verano que viene iré a Italia con mis amigos.`),
tS(`We usually go to the coast, but last year we went to the mountains.`,[` normalmente | generalmente | solemos `,` costa `,` ano pasado `,` fuimos `,` montana`],`Normalmente vamos a la costa, pero el año pasado fuimos a la montaña.`),
tS(`The best thing was the food, although the hotel was noisy.`,[` lo mejor `,` comida `,` aunque `,` hotel `,` ruidoso `],`Lo mejor fue la comida, aunque el hotel era ruidoso.`)),
one(wr(`Write a sentence in Spanish about a past holiday: say where you went and how you travelled.`,[` fui | fuimos `,` en avion | en coche | en tren | en barco | en autobus | en autocar `],`El año pasado fui a Portugal en avión con mi familia.`),
wr(`Write a sentence in Spanish saying where you will go on holiday next year and why.`,[ES.FT,ES.BC],`El año que viene voy a ir a España porque me encanta la playa.`),
wr(`Write a sentence in Spanish giving your opinion of a holiday, mentioning the weather.`,[` hizo | hacia | llovio | sol | calor | frio | tiempo `,` fue | lo pase | me gusto | me encanto | era `],`Lo pasé muy bien porque hizo sol todos los días.`)),
conj('pret',[0,1,2,4,6])]]})();
