/* Physics: step-by-step explanations for the Explain button (calculation questions).
   Each entry gives one explanation for each step of the working shown in Correction, in the same order.
   The code before each entry identifies the question type; it is made by xk() in subjects.js from the question's method text. */
Object.assign(EXPL,{
/* ---- Forces & motion ---- */
'1pp2fnh':[`Speed means how far something travels in each second. Sharing the distance equally between the seconds (dividing) gives the distance covered in one second. Metres divided by seconds gives m/s.`],
'1a7cska':[`Both forces push or pull the same way, so they help each other. Adding them gives the single force (the resultant) that would have the same effect.`],
'1avsy8x':[`The forces act against each other, so the smaller one cancels out part of the bigger one. What is left over is the resultant, and it points the way the bigger force was acting.`],
'1srat4z':[`Pressure tells you how much force presses on each square metre. Dividing the force by the area spreads the force evenly over the surface. Newtons divided by square metres gives N/m².`],
'161w6wr':[`The speed is given in metres per SECOND, so the time must also be in seconds. There are 60 seconds in each minute, so multiply the minutes by 60.`,`Each second the object covers the same distance, so multiply the distance covered in one second (the speed) by the number of seconds.`],
'a2rfi5':[`The speed tells you how many metres are covered each second. Dividing the whole distance by that amount tells you how many seconds are needed.`],
'72d37l':[`A moment is the turning effect of a force. It is bigger if the force is bigger or if it acts further from the pivot, so multiply the two. The unit combines newtons and metres: N m.`],
'167ia3f':[`Pressure is the force on each square metre. Multiplying it by the number of square metres gives the total force on the whole area.`],
'10yb10d':[`This is the turning effect of the first child: their weight multiplied by their distance from the pivot.`,`To balance, the second child must produce exactly the same moment. Moment = weight × distance, so distance = moment ÷ weight.`],
'3uhd6p':[`Add the distances of the two stages to get the whole journey.`,`Add the times of the two stages to get the whole time taken.`,`Average speed is the whole distance shared over the whole time. Averaging the two speeds would be wrong, because different amounts of time were spent at each speed.`],
'718e4z':[`Each hour, both vehicles eat into the gap, so the gap shrinks by both speeds added together.`,`Divide the starting gap by the amount it shrinks each hour to find how many hours it takes to close.`],
'1nckwj3':[`Pressure acts over the whole base, so first find how many square metres the base covers: length × width.`,`Pressure is the force on each square metre, so multiply by the number of square metres to get the total force.`],
'hohb3h':[`Each force on that side has its own turning effect (force × distance). Both turn the plank the same way, so add them. The plank's own weight acts at the pivot, a distance of zero, so its moment is zero.`,`The single force on the other side must give the same total moment. Distance = moment ÷ force.`],
'rmi10t':[`For each stage, time = distance ÷ speed. The stop counts too, because the clock keeps running; change its minutes into hours so that all the times are in the same unit.`,`Add the distances of the stages actually travelled. The stop adds no distance.`,`Average speed = total distance ÷ total time, including the time spent stopped.`],
'iok4qc':[`The elephant's weight is shared over all four feet, so use the total area of four feet. Pressure = force ÷ area.`,`All of the person's weight presses on the tiny area of one heel, so the pressure is very large.`,`To find how many times bigger one pressure is than another, divide the larger by the smaller.`],
'yzdccw':[`Weight and upthrust act vertically and are equal, so they cancel and do not affect the horizontal motion. Horizontally, the resistive forces act against the forward force, so subtract them. A positive answer means the resultant is forwards.`],
/* ---- Energy ---- */
'1bhzzgs':[`Power is the energy transferred every second. Multiply the energy per second by the number of seconds to get the total energy. Watts × seconds gives joules.`],
'x9iee':[`Energy cannot be created or destroyed, so the useful and wasted energy together must equal the total input. Take the part you know away from the total to find the other part.`],
'a3pbfe':[`Efficiency is the fraction of the input energy that ends up being useful. Dividing useful by total gives the fraction; multiplying by 100 turns it into a percentage.`],
'rsi458':[`Power is how much energy is transferred each second, so share the energy equally between the seconds. Joules divided by seconds gives watts.`],
'r1todi':[`Electricity bills use the kilowatt-hour: the energy used by a 1 kW appliance in 1 hour. Multiply the power in kW by the time in hours.`,`Each kWh costs the same amount, so multiply the number of kWh by the price of one.`],
'11cknzk':[`Work is done when a force moves something. The further it moves and the bigger the force, the more energy is transferred, so multiply. Newtons × metres gives joules.`],
'wmnmxb':[`Useful and wasted energy together make 100% of the input. Subtract the useful percentage from 100 to get the wasted percentage, then find that percentage of the input (divide by 100 and multiply).`],
'1j8g2nv':[`The power tells you how many joules are transferred each second. Dividing the total energy by this gives the number of seconds. There are 60 seconds in a minute, so divide by 60 to change to minutes.`],
'1begbct':[`Lifting works against gravity, so you need the object's weight, which is a force in newtons. Each kilogram weighs 10 N, so multiply the mass by 10.`,`The energy transferred is the work done: force × distance. Here the force is the weight and the distance is the height lifted.`],
'1akwom5':[`Each year the saving pays back part of the cost. Dividing the cost by the saving per year tells you how many years it takes to pay it all back.`],
'iqjxdb':[`The saving comes from the difference in power between the two lamps. Divide watts by 1000 to change to kilowatts, because energy bills use kWh.`,`Find the total time the lamp is on: hours per day × number of days.`,`Energy saved in kWh = power saved in kW × time in hours.`,`Multiply the kWh saved by the price of one kWh to get the money saved.`],
'5zkg9i':[`Only part of the fuel's energy becomes electricity. Find that percentage of the starting amount.`,`Some of that electricity is then wasted in the cables. The second percentage applies to what is LEFT after the first stage, not to the original amount.`],
'8xobs3':[`The useful job is lifting the load. The energy needed is the work done: weight × height.`,`Power is energy per second, so divide the useful energy by the time taken.`,`The motor is not perfectly efficient, so it must take in more power than it gives out usefully. Useful power = efficiency × input power, so input power = useful power ÷ efficiency (as a decimal).`],
'n0emzh':[`Only the height the object has actually dropped matters. Subtract the final height from the starting height.`,`The energy lost from the gravitational store is mass × g × height lost. With no friction, all of it moves into the kinetic store.`],
/* ---- Electricity ---- */
'ul9psx':[`Resistance tells you how many volts are needed to push each amp through the component. Divide the potential difference by the current. Volts ÷ amps gives ohms.`],
'1qhs9ee':[`There is only one path in a series circuit, so the same charge flows through every component each second. Current is not used up by the lamps, so every ammeter reads the same.`],
'jjh1w8':[`Each cell gives the charge another push. Cells connected the same way round in series add their pushes, so multiply the number of cells by the potential difference of one.`],
'1tdt0qp':[`Each ohm of resistance needs one volt to push one amp through it. More current or more resistance needs a bigger push, so multiply them.`],
'1lfm5k1':[`The potential difference is the push; the resistance opposes it. Dividing the push by the resistance gives the current that flows.`],
'19l28v6':[`At a junction the current splits between the branches and joins up again afterwards. No charge is lost, so the branch currents add up to the total.`],
'usr16y':[`The total current splits between the branches. Take the current in the branch you know away from the total to find what goes through the other branch.`],
'1v03sib':[`In series, the battery's push is shared out between the components. Take the potential difference across the one you know away from the battery's to find the rest.`],
'1frhhzx':[`Power is the energy transferred each second. Potential difference is the energy given to each unit of charge, and current is the charge flowing each second, so multiplying them gives energy per second: watts.`],
'1qoxydj':[`In series the current has to pass through both resistors one after the other, so their resistances add.`,`Now treat the circuit as one resistor with this total resistance: current = potential difference ÷ resistance.`],
'19htbtu':[`Power in watts means joules per SECOND, so the time must be in seconds. Multiply the minutes by 60.`,`Multiply the energy transferred each second by the number of seconds.`],
'iqmnae':[`The current has to pass through both resistors, so add them to find the total resistance.`,`Use the whole circuit to find the current: battery potential difference ÷ total resistance. This same current flows through every component in series.`,`Now look at one resistor on its own: the potential difference across it = current through it × its resistance.`],
'gxx6ez':[`Power = potential difference × current. To get the current on its own, divide the power by the potential difference.`],
'13lds43':[`Electricity bills use kilowatts. There are 1000 W in 1 kW, so divide by 1000.`,`Find the total time it is switched on: hours per day × number of days.`,`Energy in kWh = power in kW × time in hours.`,`Multiply the number of kWh by the price of one kWh.`],
's8d0r0':[`Looking at the whole circuit, total resistance = battery potential difference ÷ current.`,`In series the total is the lamp's resistance plus the unknown resistor's. Take the lamp's resistance away to leave the unknown one.`],
'1qir8x9':[`Each branch is connected directly across the battery, so it gets the full potential difference. Current in this branch = potential difference ÷ its resistance.`,`Do the same for the second branch, using its own resistance.`,`The battery supplies both branches at once, so the total current is the two branch currents added together.`],
'1mt9kz3':[`The power formula needs the potential difference, which is not given. Find it first from V = I × R.`,`Now use P = V × I with the potential difference you have just found.`],
/* ---- Magnetism & electromagnetism ---- */
'q14ged':[`Each paperclip has the same weight, so the total weight held is the number of paperclips multiplied by the weight of one.`],
'18wrbjj':[`Divide the new number of turns by the old number to see how many times stronger the electromagnet becomes.`,`The strength is proportional to the number of turns, so it can hold that many times more paperclips.`],
'1gyuqi9':[`Divide the new mass by the old mass to find how many times stronger the electromagnet needs to be.`,`The strength is proportional to the current, so the current must be increased by the same factor.`],
'oxto2f':[`The two changes each multiply the strength, so their effects multiply together.`,`Multiply the original force by this overall factor.`],
'7sn7w4':[`Divide the force wanted by the present force to find how many times stronger the electromagnet must be.`,`With the same coil, strength is proportional to current, so multiply the current by the same factor.`],
/* ---- Waves & sound ---- */
'9k9yn1':[`Sound travels the same distance every second. Multiply the distance it travels in one second (its speed) by the number of seconds.`],
'ucqp3m':[`Frequency means the number of vibrations in ONE second. Share the vibrations equally between the seconds by dividing. The unit is hertz (Hz).`],
'1eb3icz':[`Each second, a number of waves equal to the frequency pass by, and each one is one wavelength long. Multiplying gives the distance the wave travels in a second: its speed.`],
'1gqwpih':[`In the time measured, the sound has gone all the way to the cliff and all the way back. Speed × time gives this whole there-and-back distance.`,`The cliff is only half of that journey away, so divide by 2.`],
'11cw45':[`The frequency is the number of waves made every second. In several seconds there are that many times more waves, so multiply.`],
'14zx76m':[`Wave speed = frequency × wavelength. To get the wavelength on its own, divide the speed by the frequency. The answer is a length, in metres.`],
'1o0wizm':[`The pulse travels down to the sea bed and back up in the time measured. Speed × time gives the whole distance travelled.`,`The depth is only the one-way distance, so halve it.`],
'j2qmr7':[`Wave speed = frequency × wavelength. To get the frequency on its own, divide the speed by the wavelength. The answer is in hertz.`],
'12m8tbk':[`The first echo has travelled to the nearer cliff and back. Speed × time gives the there-and-back distance, so divide by 2 for the distance to that cliff.`,`Do the same with the second echo time for the further cliff.`,`The person is standing between the cliffs, so the distance between the cliffs is the two distances added together.`],
'1xuxnmn':[`Repeated timings vary a little, so use their mean: add the three times and divide by 3.`,`Speed = distance ÷ time, using the mean time.`],
'1odyehq':[`Wavelength = speed ÷ frequency gives a length in metres. There are 1000 mm in 1 m, so multiply by 1000 to change to millimetres.`],
'109075v':[`The speed is not given directly, but speed = frequency × wavelength.`,`Now that you know how far the wave travels each second, divide the distance by the speed to find the time taken.`],
/* ---- Matter & particle model ---- */
'15x9gq8':[`Density tells you how much mass is packed into each cubic centimetre. Share the mass equally between the cubic centimetres by dividing. Grams ÷ cm³ gives g/cm³.`],
'1ku1fjf':[`The stone takes up space, so it pushes the water level up by exactly its own volume. Subtract the first reading from the second.`],
'12j1hmj':[`Density is the mass of each cubic centimetre. Multiply it by the number of cubic centimetres to get the mass of the whole object.`],
'1oe16wg':[`The density tells you how many grams are in each cubic centimetre. Dividing the total mass by that tells you how many cubic centimetres there are.`],
'hm4pcx':[`A block's volume is the space it takes up: length × width × height, in cm³.`,`Now share the mass between those cubic centimetres: density = mass ÷ volume.`],
'1yacj24':[`The water level rises by the volume of the stone, so subtract the starting level from the new level.`,`Density = mass ÷ volume, using the volume you have just found.`],
'1ck0trk':[`Density is the mass of each cubic centimetre, so the total mass is the density multiplied by the number of cubic centimetres.`],
'1xso4yk':[`Density × volume gives the mass in grams. There are 1000 g in 1 kg, so divide by 1000 to change to kilograms.`],
'170k1mg':[`Density = mass ÷ volume. Every pure material has its own density, so if the answer does not match the density of gold, the ring cannot be pure gold.`],
'kneib4':[`You cannot average densities, because the two parts have different sizes. Instead find the mass of each part (density × volume) and add them.`,`Add the two volumes to get the volume of the whole object.`,`Density of the whole object = total mass ÷ total volume.`],
'mcfdde':[`The tank's volume is length × width × height, in m³.`,`Mass = density × volume. With density in kg/m³ and volume in m³, the mass comes out in kilograms.`,`Weight is the force of gravity on the mass: each kilogram weighs 10 N, so multiply by 10.`],
'12r3pr2':[`All the marbles together push the water level up by their total volume, so subtract the starting level from the final level.`,`Every marble is made of the same glass, so density = total mass ÷ total volume.`],
/* ---- Space ---- */
'a64748':[`Weight is the force of gravity on an object. Each kilogram is pulled with a force equal to the field strength, so multiply the mass by the field strength. The answer is a force, in newtons.`],
'f7tey0':[`Weight = mass × field strength. To get the mass on its own, divide the weight by the field strength. The answer is in kilograms.`],
'vhuxk8':[`The field strength is the force on each kilogram. Share the weight equally between the kilograms by dividing. Newtons ÷ kilograms gives N/kg.`],
'gj42cx':[`On Earth, weight = mass × Earth's field strength.`,`The mass is the same on the other planet, but the field strength is different, so work out the weight there separately.`,`Subtract the smaller weight from the larger to find the difference.`],
'11o5huw':[`Mass does not change from place to place, so find it first using the Earth values: mass = weight ÷ field strength.`,`On the Moon the same mass is pulled less strongly. Multiply the mass by the Moon's field strength.`],
'5ca4c9':[`Light covers the same distance every second. Dividing the whole distance by the distance covered in one second gives the number of seconds. Both must be in the same unit (km).`],
'8uu00j':[`The orbit time is given in minutes, so change the day into minutes too: 24 hours × 60.`,`Divide the minutes in a day by the minutes for one orbit to find how many orbits fit into a day.`],
'45exda':[`The Moon's gravity pulls on the astronaut and the suit together, so add their masses.`,`Weight = total mass × the field strength of the place where the astronaut is standing, which is the Moon.`],
'1arcxqp':[`Time = distance ÷ speed gives the time for the signal to travel one way.`,`A reply has to come all the way back as well, so the total wait is double.`],
'19algvy':[`Mass is the same everywhere, so use the Earth measurements to find it: mass = weight ÷ field strength.`,`On planet X, field strength = weight there ÷ mass. This is the force on each kilogram.`],
'u8b6iz':[`The speed is in km per SECOND, so the time must be in seconds: multiply the minutes by 60.`,`Distance = speed × time: the distance covered each second multiplied by the number of seconds.`],
/* ---- Practical & investigation skills ---- */
'lkfrxv':[`The mean shares the total equally between the readings. Add all the readings, then divide by how many there are. It gives a fairer value than any single reading.`],
'14yvju7':[`The length is the gap between the two ends on the scale. Because the object does not start at zero, subtract the starting reading from the end reading.`],
'sxh7ky':[`A metre is 100 times bigger than a centimetre, so the number of metres is 100 times smaller. Divide by 100.`],
'fwmt8k':[`An anomaly is a result that does not fit the pattern of the others, usually because of a mistake. Including it would pull the mean away from the true value.`,`Find the mean of the remaining results: add them and divide by how many there are.`],
'1u3btyp':[`The range shows how spread out the readings are. Subtract the smallest from the largest.`],
'1prj0mj':[`The gradient is how much the line goes up for each one unit it goes across. Divide the rise (change in y) by the run (change in x).`],
'1tjnjfb':[`The range is the spread of the repeat readings: largest minus smallest.`,`The true value is probably near the middle of the spread, so the uncertainty is half the range. It is written as the mean plus or minus this amount.`],
'1o16j8s':[`Divide the new load by the old load to find how many times bigger it is.`,`Because extension is directly proportional to load, the extension gets bigger by the same factor.`],
'rdze1m':[`Pick two neighbouring numbered marks and find the difference between them.`,`That difference is shared equally between the small divisions, so divide by the number of divisions to find what each one is worth.`],
'7eg0r8':[`One time is very different from the others, probably a timing mistake, so leave it out.`,`Find the mean of the other times: add them and divide by how many there are.`,`Speed = distance ÷ time, using the mean time.`],
'2euyje':[`Find how far the measured value is from the true value by subtracting.`,`Compare that difference with the true value: divide by the true value and multiply by 100 to give a percentage.`],
'ovtkre':[`On a distance–time graph the speed is the gradient. Take two points on the line: the change in distance divided by the change in time. Using differences matters because the line does not start at zero.`],
'457ast':[`All the swings take the same time, so the time for one is the total time divided by the number of swings. Timing many swings makes any error in starting and stopping the stopwatch a much smaller part of the result.`]
});
